---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - name: Load variables
      ansible.builtin.include_vars:
        file: vars.yml

    - name: Install Postgres
      ansible.builtin.include_role:
        name: "postgres"
      when: "'postgres' in group_names"

    - name: Install PgPool II
      ansible.builtin.include_role:
        name: "postgres"
      when: "'pgpool' in group_names"