---
basic_packages: [ ]
user_accounts: [ ]
firewall:
  enabled: false
  rules: [ ]

databases: []

users: []

replication_user:
  name: replication
  database: replication
  password: test

pgpool_user:
  name: pgpool
  database: all
  password: test