---
# inventories file pgpool local group
postgres_instances: "{{ groups['postgres'] | list }}"
database_subnet: "0.0.0.0/0"

firewall:
  enabled: true
  rules:
    - name: pgpool
      port: 9999
      policy: allow
      direction: in
      protocol: tcp
    - name: pcp
      port: 9898
      policy: allow
      direction: in
      protocol: tcp