---
# inventories file postgres local group
master_ip_address: "{{ groups['master'] | first }}"
database_subnet: "0.0.0.0/0"

firewall:
  enabled: true
  rules:
    - name: postgres
      port: 5432
      policy: allow
      direction: in
      protocol: tcp

databases:
  - name: orders
