---
# inventories file database local group
pgpool_enabled: true
pgpool_ip_address: "{{ hostvars['pgpool.local']['ansible_host'] }}"

users:
  - name: program
    database: orders
    password: "{{ vault_program_passwd }}"
    privilege: ALL
    attributes:
      - LOGIN

replication_user:
  name: replication
  database: replication
  password: "{{ vault_replication_passwd }}"

pgpool_user:
  name: pgpool
  database: all
  password: "{{ vault_pgpool_passwd }}"
