---
# file: inventories/local/hosts.yml
all:
  hosts:
    postgres-master.local:
    postgres-slave.local:
    pgpool.local:
  children:
    master:
      hosts:
        postgres-master.local:
    slave:
      hosts:
        postgres-slave.local:
    pgpool:
      hosts:
        pgpool.local:
    postgres:
      children:
        master:
        slave: