---
# file: inventories/local/hosts.yml
all:
  hosts:
    postgres-master.local:
      ansible_host: "192.168.56.100"
    postgres-slave.local:
      ansible_host: "192.168.56.101"
    pgpool.local:
      ansible_host: "192.168.56.102"
  children:
    master:
      hosts:
        postgres-master.local:
    slave:
      hosts:
        postgres-slave.local:
    pgpool:
      hosts:
        pgpool.local:
    postgres:
      children:
        master:
        slave: