---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Load variables
      ansible.builtin.include_vars:
        file: vars.yml

    - name: Include Postrges
      ansible.builtin.include_role:
        name: postgres
