---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: postgres-master
    hostname: postgres-master.local
    box: romanow/ansible-box
    box_version: 22.04
    memory: 1024
    cpus: 1
    instance_raw_config_args:
      - 'ssh.username = "ansible"'
      - 'ssh.password = "root"'
    interfaces:
      - network_name: private_network
        ip: 192.168.56.100
    groups:
      - master
    children:
      - postgres

  - name: postgres-slave
    hostname: postgres-slave.local
    box: romanow/ansible-box
    box_version: 22.04
    memory: 1024
    cpus: 1
    instance_raw_config_args:
      - 'ssh.username = "ansible"'
      - 'ssh.password = "root"'
    interfaces:
      - network_name: private_network
        ip: 192.168.56.101
    groups:
      - slave
    children:
      - postgres

provisioner:
  name: ansible
  config_options:
    defaults:
      vault_password_file: "${MOLECULE_SCENARIO_DIRECTORY}/.vault_pass"
  inventory:
    inventory:
      host_vars:
        ubuntu:
          ansible_python_interpreter: "/usr/bin/python3"
    links:
      group_vars: ${MOLECULE_PROJECT_DIRECTORY}/../../inventories/local/group_vars/
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint