---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name:  postgres-master.local
    image: ubuntu:22.04
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    docker_networks:
      - name: cluster
        ipam_config:
          - subnet: "192.168.0.0/24"
            gateway: "192.168.0.254"
    exposed_pors:
      - 5432/tcp
    networks:
      - name: cluster
        ipv4_address: "192.168.0.10"
    groups:
      - postgres
      - master

  - name:  postgres-slave.local
    image: ubuntu:22.04
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    exposed_pors:
      - 5432/tcp
    networks:
      - name: cluster
        ipv4_address: "192.168.0.11"
    groups:
      - postgres
      - slave

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      allow_world_readable_tmpfiles: true
  inventory:
    group_vars:
      postgres:
        master_ip_address: "192.168.0.10"
        slave_ip_address: "192.168.0.11"
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint