---
# access task for postgres
- name: Configure user access
  community.postgresql.postgresql_pg_hba:
    dest: "{{ postgres.conf_dir }}/pg_hba.conf"
    contype: host
    method: md5
    databases: "{{ item.database }}"
    users: "{{ item.name }}"
    source: 0.0.0.0/0
  with_items: "{{ users }}"

- name: Configure replication access
  community.postgresql.postgresql_pg_hba:
    dest: "{{ postgres.conf_dir }}/pg_hba.conf"
    contype: host
    method: scram-sha-256
    databases: "{{ replication_user.database }}"
    users: "{{ replication_user.name }}"
    source: "{{ database_subnet }}"

- name: Configure PgPool access
  community.postgresql.postgresql_pg_hba:
    dest: "{{ postgres.conf_dir }}/pg_hba.conf"
    contype: host
    method: scram-sha-256
    databases: "{{ pgpool_user.database }}"
    users: "{{ pgpool_user.name }}"
    source: "{{ database_subnet }}"
  when: pgpool_user is defined

- name: Restart Postgres
  ansible.builtin.service:
    name: postgresql
    state: restarted