---
# configure task for postgres
- name: Install required library
  block:
    - apt:
        name: libpq-dev
        state: fixed
    - pip:
        name: psycopg2

- name: Configure Postrges
  template:
    src: "templates/postgres.conf.j2"
    dest: "{{ postgres.conf_dir }}/postgresql.conf"
    owner: postgres
    group: postgres
    mode: 0644
  notify:
    - restart postgres

- name: Configure Master node
  include_tasks:
    file: master.yml
    apply:
      tags: [ all, postgres, configure ]
  when: "'master' in group_names"

- name: Configure Slave node
  include_tasks:
    file: slave.yml
    apply:
      tags: [ all, postgres, configure ]
  when: "'slave' in group_names"