---
# configure task for postgres
- name: Install required library
  block:
    - name: Install libpq-dev
      ansible.builtin.apt:
        name: libpq-dev
        state: fixed
    - name: Install psycopg2
      ansible.builtin.pip:
        name: psycopg2

- name: Configure Postrges
  ansible.builtin.template:
    src: templates/postgres.conf.j2
    dest: "{{ postgres.conf_dir }}/postgresql.conf"
    owner: postgres
    group: postgres
    mode: 0644

- name: Configure users
  ansible.builtin.include_tasks:
    file: users.yml
    apply:
      tags: [ all, postgres, configure ]

- name: Set PgPool ssh key
  ansible.posix.authorized_key:
    key: "{{ pgpool_public_key }}"
    user: postgres
    state: present
  when: pgpool_enabled

- name: Configure PCP passwordless access
  ansible.builtin.copy:
    dest: "~/.pcppass"
    content: "{{ pgpool_ip_address }}:9898:pgpool:{{ pgpool_user.password }}"
    owner: postgres
    group: postgres
    mode: 0600
  become_user: postgres
  become: true
  when: pgpool_enabled

- name: Configure Slaves node
  ansible.builtin.include_tasks:
    file: slave.yml
    apply:
      tags: [all, postgres, configure]
  when: "'slaves' in group_names"
