---
# install task for postgres
- name: Add Postrges key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add Postgres repository
  ansible.builtin.apt_repository:
    repo: deb https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
    update_cache: true
    state: present

- name: Install Postgres {{ postgres.version }}
  ansible.builtin.apt:
    name: postgresql-{{ postgres.version }}
    state: present

- name: Ensure Postgres service is running
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true
