---
# master task for postgres
- name: Create users
  community.postgresql.postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    role_attr_flags: "{{ item.attributes | join(',') }}"
  environment:
    PGOPTIONS: -c password_encryption=scram-sha-256
  with_items: "{{ users }}"
  become_user: postgres
  become: true

- name: Create databases
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"

  with_items: "{{ databases }}"
  become_user: postgres
  become: true

- name: Grant privileges to users
  community.postgresql.postgresql_privs:
    role: "{{ item.name }}"
    database: "{{ item.database }}"
    privs: "{{ item.privilege }}"
    type: schema
    objs: public
  with_items: "{{ users }}"
  become_user: postgres
  become: true

- name: Create replication user
  community.postgresql.postgresql_user:
    name: "{{ replication_user.name }}"
    password: "{{ replication_user.password }}"
    role_attr_flags: REPLICATION,LOGIN
  environment:
    PGOPTIONS: -c password_encryption=scram-sha-256
  become_user: postgres
  become: true

- name: Create PgPool user
  community.postgresql.postgresql_user:
    name: "{{ pgpool_user.name }}"
    password: "{{ pgpool_user.password }}"
    role_attr_flags: SUPERUSER
  environment:
    PGOPTIONS: -c password_encryption=scram-sha-256
  become_user: postgres
  become: true
