---
- name: Converge
  hosts: all
  tasks:
    - name: Load variables
      ansible.builtin.include_vars:
        file: vars.yml
    - name: Include basic
      ansible.builtin.include_role:
        name: basic
