# Molecule managed
FROM ${MOLECULE_IMAGE}:${MOLECULE_VERSION}

ENV MOLECULE_VERSION
ENV MOLECULE_IMAGE

RUN apt-get update && \
    apt-get install sudo bash ufw ca-certificates python3 python3-pip python3-apt python3-distutils-extra gnupg systemctl -y && \
    apt-get clean