# Molecule managed
FROM ${MOLECULE_IMAGE}:${MOLECULE_VERSION}

ARG MOLECULE_IMAGE
ARG MOLECULE_VERSION

ENV IMAGE=${MOLECULE_IMAGE}
ENV VERSION=${MOLECULE_VERSION}

RUN apt-get update && \
    apt-get install sudo bash ufw ca-certificates python3 python3-pip python3-apt python3-distutils-extra gnupg systemctl -y && \
    apt-get clean