FROM {{ item.image }}
RUN apt-get update && \
    apt-get install -y \
        sudo bash ufw \
        ca-certificates \
        python3 python3-pip python3-apt \
        python3-distutils-extra gnupg \
        systemctl -y && \
    apt-get clean