---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: ubuntu:22.04
    privileged: true
    env:
      MOLECULE_IMAGE: "${MOLECULE_IMAGE}"
      MOLECULE_VERSION: "${MOLECULE_VERSION}"
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
lint: |-
  yamllint .
  ansible-lint
