---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: ${MOLECULE_IMAGE:-ubuntu}:${MOLECULE_VERSION:-22.04}
    privileged: true
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
lint: |-
  yamllint .
  ansible-lint
