---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: "geerlingguy/docker-${MOLECULE_IMAGE:-ubuntu2204}-ansible:latest"
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
lint: |-
  yamllint .
  ansible-lint
