---
# meta file for basic
galaxy_info:
  role_name: basic
  namespace: romanowalex
  author: Romanov Alex (romanowalex@mail.ru)
  description: Basic configuration
  license: Apache-2.0
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
