---
# firewall task for basic
- name: Enable SSH
  community.general.ufw:
    rule: allow
    port: ssh
    comment: ssh

- name: Configure IPtables
  community.general.ufw:
    rule: "{{ item.policy }}"
    direction: "{{ item.direction }}"
    port: "{{ item.port }}"
    proto: "{{ item.protocol }}"
    comment: "{{ item.name | default('') }}"
  with_items:
    - "{{ firewall.rules }}"
  notify:
    - Restart Firewall

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming
