---
# user task for basic
- name: Create user {{ item.name }}
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: ""
    groups: "{{ item.groups + [developer_group] }}"
    shell: "{{ item.shell }}"
    comment: "{{ item.comment }}"
    update_password: on_create
    append: true
  register: user_updated

- name: Expire password {{ item.name }}
  ansible.builtin.shell: passwd -e {{ item.name }}
  when: user_updated.changed

- name: Add SSH key for {{ item.name }}
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.public_key }}"
    state: present
  when: item.public_key is defined
