---
# user task for basic
- name: Create user {{ item.name }}
  user:
    name: "{{ item.name }}"
    password: ""
    groups: "{{ item.groups + [ developer_group ] }}"
    shell: "{{ item.shell }}"
    comment: "{{ item.comment }}"
    update_password: on_create
    append: yes
  register: user_updated

- name: Expire {{ item.name }} password
  shell: "passwd -e {{ item.name }}"
  when: user_updated.changed

- name: Add SSH key for {{ item.name }}
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.public_key }}"
    state: present