---
# users task for basic
- name: Create group {{ developer_group }}
  ansible.builtin.group:
    name: "{{ developer_group }}"
    state: present

- name: Get existing users
  ansible.builtin.shell: 'grep developers /etc/group | cut -d: -f4 | tr "," "\n"'
  changed_when: false
  register: existing_users

- name: Existing users
  ansible.builtin.debug:
    msg: "{{ existing_users.stdout_lines }}"
  tags: [never, debug]
- name: Calculate users
  ansible.builtin.set_fact:
    users_for_remove: "{{ existing_users.stdout_lines | difference(user_accounts | map(attribute='name')) }}"

- name: Users for remove
  ansible.builtin.debug:
    msg: "{{ users_for_remove }}"
  tags: [never, debug]
- name: Create users
  ansible.builtin.include_tasks: user.yml
  with_items: "{{ user_accounts }}"

- name: Delete users {{ users_for_remove }}
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
    remove: true
  with_items: "{{ users_for_remove }}"
