---
# inventories file pgpool local group
postgres_instances: "{{ groups['postgres'] | map('extract', hostvars, ['ansible_host']) | list }}"
database_subnet: "{{ ''.join(pgpool_ip_address, '/16') | ansible.utils.ipaddr('network/prefix') }}"

firewall:
  enabled: true
  rules:
    - name: pgpool
      port: 9999
      policy: allow
      direction: in
      protocol: tcp
    - name: pcp
      port: 9898
      policy: allow
      direction: in
      protocol: tcp