---
# main defaults file for basic
pgpool_enabled: true
pgpool_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBx7e38ggztYOnjRF5oQNuY+xlf2+8/30XrBFRfs+vwXzFu6D+Xd1xJxbuBlsdX1LJj5mtjU7wyA6ZGIlG//BYp5JcIfMvVw0GIy6vRLgSwW/ci36Q+UMbiuDd+fQxX+HJkDNc/Gszi7xbEsoD3RFkVkb40IrbqIOfhckHXOcYKZ5duMCrL7icRll+BZkXBrgFFKx6kh5MrxU6Fwdz8NI3CoyCV4Y4yEhEXnCQGhxia7Fm56vwfa8e4e9aNUwXbgW1wL8svhCITd6rln7uuvfOGBILStcK1gSBpYSAjELBznlw+ssAg6GUgbNh4MnVjEveBEmbtjQ31EUk2tDkZcolVsDgl8j9pwaBCFqhJYEuLVCdSG9G+1lT7NVRx+cHznRDUMfqcHbSK4K/lr8f54X0p6j1+A1C0BlOlMWpC0vJ63OOxovyw25R3yEMuxZ1Bx15/nf5VuAVaM6TDcW+IavxhUmRTs+gGvGdZy8/MjblC+dsaIZ5AXHmdJaep7Z3RDk= aromanov@aromanov.local"

storage_type: ssd
random_page_cost_ssd: 1.1
random_page_cost_hdd: 4
effective_io_concurrency_ssd: 200
effective_io_concurrency_hdd: 2
max_connections: 100
shared_buffers: "{{ (ansible_memtotal_mb / 4) | round | int }}"
worker_threads: "{{ ansible_processor_cores * ansible_processor_threads_per_core }}"

postgres:
  version: 15
  conf_dir: /etc/postgresql/15/main
  data_dir: /var/lib/postgresql/15/main
  log_dir: /var/log/postgresql
  run_dir: /var/run/postgresql
  timezone: Europe/Moscow
  listen_port: 5432
  listen_addresses: "*"
  max_connections: "{{ max_connections }}"
  config:
    shared_buffers: "{{ shared_buffers }}MB"
    work_mem: "{{ ((ansible_memtotal_mb - shared_buffers|int) * 1024 / (max_connections * worker_threads|int * 3)) | round|int }}kB"
    effective_cache_size: "{{ (ansible_memtotal_mb * 3 / 4) | round | int }}MB"
    maintenance_work_mem: "{{ (ansible_memtotal_mb / 16) | round | int }}MB"
    random_page_cost: "{{ (storage_type == 'ssd') | ternary(random_page_cost_ssd, random_page_cost_hdd) }}"
    effective_io_concurrency: "{{ (storage_type == 'ssd') | ternary(effective_io_concurrency_ssd, effective_io_concurrency_hdd) }}"
    checkpoint_completion_target: 0.7
    default_statistics_target: 100
  replication:
    wal_buffers: "{{ (shared_buffers|int * 3 / 100) | round | int }}MB"
    min_wal_size: 1GB
    max_wal_size: 4GB

databases: []
users: []
replication_user:
  name: replication
  database: replication
  password: "{{ vault_replication_passwd }}"

pgpool_user:
  name: pgpool
  database: all
  password: "{{ vault_pgpool_passwd }}"
