---
# file: inventories/local/hosts.yml
all:
  hosts:
    postgres-master:
      ansible_host: "192.168.56.100"
    postgres-slave:
      ansible_host: "192.168.56.101"
  children:
    postgres:
      children:
        master:
          hosts:
            postgres-master:
        slave:
          hosts:
            postgres-slave: