name: build
on:
  push:
    branches: [ master ]
jobs:
  terraform:
    name: Terrafrom
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Check Terraform
        run: |-
          cd terraform
          terraform fmt -check
          terraform init
          terraform validate

  ansible:
    name: Ansible
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Install requirements
        run: |-
          pip3 install -r ansible/requirements.txt

      - name: Test Scenarious
        run: |-
          shopt -s extglob

          base_folder=$(pwd)
          for dir in ansible/roles/*; do
            cd "$dir"
            molecule converge
            cd "$base_folder"
          done
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

