name: build
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test Scenarious
        run: |-
          shopt -e
          pip3 install -r requirements.txt
          for dir in ./roles/*; do
            cd "$dir"
            molecule converge
          done
