name: build
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Check Terraform
        run: |-
          cd terraform
          terraform fmt -check
          terraform init
          terraform validate

      - name: Test Scenarious
        run: |-
          shopt -s extglob
          cd ansible
          pip3 install -r requirements.txt
          for dir in roles/*; do
            (cd "$dir"; molecule converge)
          done
